### ISSUE TITLE
allow for size constraints using conventional units

### ISSUE THREAD

**Issue by binaryartifex** [hugeicons/hugeicons#4]
Is it possible, or is there a wrapper im not aware of that allows for the constraining of these icons to something like em's? ie. if the base viewbox is 0 0 24 24 (it looks like it is universally across the icon set) then by setting the width and height to 1em, i can either constrain or inherit from font sizing in my css rules instead of having to rely on passing size props in my components ...the svgr online playground [here](https://react-svgr.com/playground/?icon=true&typescript=true) is a perfect example of what im talking about.

**Comment by boar-is** [comment]
```css
.parent {
  font-size: 24px; // this changes icon's size
}

svg {
  width: 1em;
  height: 1em;
}
```
